---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jinja-backend-conf
  labels:
    name: jinja-backend-conf
  namespace: jinja
data:
  application.conf: |-
    LOG_LOCATION = "app.log"
    LOG_FORMAT = "%(asctime)s %(levelname)s: %(message)s"

  nginx.conf: |-
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;

    events {
        worker_connections 1024;
        use epoll;
        multi_accept on;
    }

    http {
        access_log /dev/stdout;
        error_log /dev/stdout;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        index   index.html index.htm;

        server {
            listen       0.0.0.0:9090;
            server_name  localhost;
            root         /var/www/html;

            location /render_jinja {
                include uwsgi_params;
                uwsgi_pass unix:/tmp/uwsgi.sock;
            }
        }
    }

  uwsgi.ini: |-
    [uwsgi]
    module = wsgi:app

    master = true
    processes = 5

    uid = www-data
    gid = www-data

    socket = /tmp/uwsgi.sock
    chmod-socket = 664
    vacuum = true

    die-on-term = true

  supervisord.conf: |-
    [supervisord]
    nodaemon=true

    [program:uwsgi]
    command=/usr/local/bin/uwsgi --ini /app/uwsgi.ini
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    [program:nginx]
    command=/usr/sbin/nginx -g "daemon off;"
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
