---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jinja-backend
  namespace: jinja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jinja-backend
  template:
    metadata:
      name: jinja-backend
      labels:
        app: jinja-backend
    spec:
      containers:
      - name: jinja-backend
        image: penmetsa29/jinja-backend:v1
        ports:
        - name: jinja-backend
          containerPort: 9090
        volumeMounts:
          - name: jinja-backend-config-volume
            mountPath: /etc/nginx/
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
      volumes:
        - name: jinja-backend-nginx-volume
          configMap:
            defaultMode: 420
            name: jinja-backend-nginx-conf
