---
apiVersion: v1
kind: Service
metadata:
  name: jinja-backend-svc
  namespace: jinja
spec:
  selector:
    app: jinja-backend
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 32100
